apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
spec:
  rules:
    - host: emergency.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emergency-room-service
                port:
                  name: http
