apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: spring-cloud-kubernetes-reference-architecture
build:
  artifacts:
    - image: codification/emergency-room-service
      context: emergency-room-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/roles/*.yaml
    - k8s/mongo/*.yaml
    - k8s/emergency-room-service/*.yaml
    - k8s/kafka/*.yaml
portForward:
  - resourceType: service
    resourceName: emergency-room-service
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: mongodb
    port: 27017
    localPort: 27017
