apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: spring-cloud-kubernetes-reference-architecture--
build:
  artifacts:
    - image: codification/organisation
      context: organisation-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/roles/*.yaml
    - k8s/mongo/*.yaml
    - k8s/organisation-service/*.yaml
