apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: spring-cloud-kubernetes-reference-architecture
build:
  artifacts:
    - image: codification/emergency-room-service
      context: emergency-room-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
#    - k8s/mongo/mongodb-configmap.yaml
#    - k8s/mongo/mongodb-secret.yaml
#    - k8s/mongo/mongodb-deployment.yaml
    - k8s/roles/roles.yaml
