apiVersion: apps/v1
kind: Deployment
metadata:
  name: emergency-room-service
  labels:
    app: emergency-room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emergency-room-service
  template:
    metadata:
      labels:
        app: emergency-room-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: emergency-room-service
        image: mercangel/emergency-room-service:635d-20241213-1923-58
        ports:
        - containerPort: 8282
        env:
          - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
            value: "true"
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
            value: "true"