apiVersion: v1
kind: Service
metadata:
  name: emergency-room-service
  labels:
    app: emergency-room-service
    spring-boot: "true"
spec:
  ports:
    - port: 8282
      protocol: TCP
      name: http
  selector:
    app: emergency-room-service
  type: ClusterIP