apiVersion: v1
kind: Service
metadata:
  name: patients-analyzer
  labels:
    app: patients-analyzer
    spring-boot: "true"
spec:
  ports:
    - port: 8383
      protocol: TCP
  selector:
    app: patients-analyzer
  type: ClusterIP