kind: ConfigMap
apiVersion: v1
metadata:
  name: emergency-room-service
  namespace: spring-cloud-app
data:
  application.properties: |-
    spring.data.mongodb.host: mongodb
    spring.data.mongodb.database: admin
    spring.data.mongodb.authentication-database: admin