apiVersion: v1
kind: Service
metadata:
  name: emergency-room-service
  namespace: spring-cloud-app
  labels:
    app: emergency-room-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: emergency-room-service
  type: ClusterIP