apiVersion: apps/v1
kind: Deployment
metadata:
  name: organisation
  labels:
    app: organisation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organisation
  template:
    metadata:
      labels:
        app: organisation
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: organisation
        image: codification/organisation
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
            value: "true"
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
            value: "true"