apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
    spring-boot: "true"
spec:
  ports:
    - port: 8282
      protocol: TCP
  selector:
    app: config-server
  type: ClusterIP