name: Build, Tag, and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build emergency-room-service with Maven
        working-directory: ./emergency-room-service
        run: mvn clean package

      - name: Build config-server with Maven
        working-directory: ./config-server
        run: mvn clean package

      - name: Build patients-analyzer with Maven
        working-directory: ./patients-analyzer
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get the last 4 characters of the commit SHA and timestamp
      - name: Generate short SHA and timestamp
        id: tag_info
        run: |
          SHORT_SHA=${GITHUB_SHA::4}
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Build and push emergency-room-service
        uses: docker/build-push-action@v4
        with:
          context: ./emergency-room-service
          file: ./emergency-room-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/emergency-room-service:latest
            ${{ secrets.DOCKER_USERNAME }}/emergency-room-service:${{ env.SHORT_SHA }}-${{ env.TIMESTAMP }}

      - name: Build and push config-server
        uses: docker/build-push-action@v4
        with:
          context: ./config-server
          file: ./config-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/config-server:latest
            ${{ secrets.DOCKER_USERNAME }}/config-server:${{ env.SHORT_SHA }}-${{ env.TIMESTAMP }}

      - name: Build and push patients-analyzer
        uses: docker/build-push-action@v4
        with:
          context: ./patients-analyzer
          file: ./patients-analyzer/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/patients-analyzer:latest
            ${{ secrets.DOCKER_USERNAME }}/patients-analyzer:${{ env.SHORT_SHA }}-${{ env.TIMESTAMP }}