name: Build, Tag, Push Docker Images, and Update Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - emergency-room-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./${{ matrix.service }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate short SHA and timestamp
        id: tag_info
        run: |
          SHORT_SHA=${GITHUB_SHA::4}
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            mercangel/${{ matrix.service }}:latest
            mercangel/${{ matrix.service }}:${{ env.SHORT_SHA }}-${{ env.TIMESTAMP }}

      - name: Update deployment YAML with new SHA
        run: |
          IMAGE_TAG="${{ env.SHORT_SHA }}-${{ env.TIMESTAMP }}"
          FILE_PATH="deployment/dev/${{ matrix.service }}/deployment.yaml"
          sed -i "s|image: mercangel/${{ matrix.service }}:.*|image: mercangel/${{ matrix.service }}:${IMAGE_TAG}|" $FILE_PATH

      - name: Commit and push updated YAML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment/dev/${{ matrix.service }}/deployment.yaml
          git commit -m "Update image tag for ${{ matrix.service }} to ${{ env.SHORT_SHA }}-${{ env.TIMESTAMP }}"
          git push
